apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: documents
  namespace: {{ .Release.Namespace }}
  labels:
    app: dolibarr
    tenant: {{ .Values.instance | quote }}
    app.kubernetes.io/managed-by: saasplatform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{- if .Values.db.storageClass -}}
  storageClassName: {{ .Values.db.storageClass | quote }}
{{- end -}}
